### ISSUE TITLE
ModelRunner cannot navigate native Mac compressed files 

### ISSUE THREAD

**Issue by carbz** [SEL-Columbia/modelrunner#19]
ModelRunner is sensitive to compressed file types.  If compressing a folder in Mac environment, you will will consistently face FAILED jobs in modelrunner.

modelrunner is looking for all the input files it needs in the top level directory of the zip file.  An example of the directory it sees from a Mac .zip is as such:  http://23.253.225.19:8888/worker_data/9046da92-c1cb-458c-8db8-062b75df32c4/input/

Therefore when it can't find networks-proposed.shp in that root dir of the zip, it chokes.

**Comment by carbz** [comment]
Resulting error message:
>>
reading input from /home/mr/model_runner/worker_data/5f25fb20-e50d-4cc3-a6ed-50ef33bb219f/input
discarding /home/mr/miniconda/envs/model_runner/bin from PATH
prepending /home/mr/miniconda/envs/sequencer/bin to PATH
2015-04-13 13:57:14,959 : NetworkPlan [INFO] : Asserting Input Projections Match
Traceback (most recent call last):
  File "/home/mr/model_runner/scripts/mvmax_sequencer.py", line 19, in <module>
    nwp = NetworkPlan(shp_file, csv_file, prioritize='Population')
  File "/home/mr/miniconda/envs/sequencer/lib/python2.7/site-packages/sequencer/NetworkPlan.py", line 48, in __init__
    self._assert_proj_match(shp, csv)
  File "/home/mr/miniconda/envs/sequencer/lib/python2.7/site-packages/sequencer/NetworkPlan.py", line 108, in _assert_proj_match
    shapefile = fiona.open(shp)
  File "/home/mr/miniconda/envs/sequencer/lib/python2.7/site-packages/fiona/__init__.py", line 137, in open
    raise IOError("no such file or directory: %r" % path)
IOError: no such file or directory: '/home/mr/model_runner/worker_data/5f25fb20-e50d-4cc3-a6ed-50ef33bb219f/input/networks-proposed.shp

**Comment by carbz** [comment]
Seems related to previous issue #17

**Comment by chrisnatali** [comment]
@Naigege is this still an issue?

**Comment by Naigege** [comment]
@chrisnatali Not anymore. Thanks!

**Comment by chrisnatali** [comment]
Great.
