### ISSUE TITLE
MemoryError happening 

### ISSUE THREAD

**Issue by Naigege** [SEL-Columbia/modelrunner#23]
When kedco-all zip file run on model runner, it gives a memory error shown as below. The uploaded zip file is 10mb.

reading input from /home/mr/model_runner/worker_data/011a8c4b-2f0a-439d-bffb-1faa030b5b60/input
discarding /home/mr/miniconda/envs/model_runner/bin from PATH
prepending /home/mr/miniconda/envs/sequencer/bin to PATH
2015-04-30 20:40:38,011 : NetworkPlan [INFO] : Asserting Input Projections Match
2015-04-30 20:40:41,108 : NetworkPlan [INFO] : Aligning Network Nodes With Input Metrics
/home/mr/miniconda/envs/sequencer/lib/python2.7/site-packages/sequencer/Utils.py:61: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  fake_nodes['m_coords'] = fake_nodes['m_coords'].apply(lambda x: ())
2015-04-30 20:41:02,613 : NetworkPlan [INFO] : Computing Pairwise Distances
2015-04-30 20:41:02,613 : NetworkPlan [INFO] : Using haversine Distance
Traceback (most recent call last):
  File "/home/mr/model_runner/scripts/mvmax_sequencer.py", line 19, in <module>
    nwp = NetworkPlan(shp_file, csv_file, prioritize='Population')
  File "/home/mr/miniconda/envs/sequencer/lib/python2.7/site-packages/sequencer/NetworkPlan.py", line 58, in __init__
    self.distance_matrix = self._distance_matrix()
  File "/home/mr/miniconda/envs/sequencer/lib/python2.7/site-packages/sequencer/NetworkPlan.py", line 97, in _distance_matrix
    return np.vstack(map(haversine, coords))
  File "/home/mr/miniconda/envs/sequencer/lib/python2.7/site-packages/numpy/core/shape_base.py", line 228, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
MemoryError

**Comment by carbz** [comment]
Confirming this issue still exists. Tested full KEDCO dataset via networker found here
http://23.253.225.19:8888/worker_data/d75771fb-f073-4c88-95c8-a82f368720ec/job_log.txt

Similar error message results... 

>>reading input from /home/mr/modelrunner/worker_data/d75771fb-f073-4c88-95c8-a82f368720ec/input
discarding /home/mr/miniconda/envs/modelrunner/bin from PATH
prepending /home/mr/miniconda/envs/sequencer/bin to PATH
2015-05-14 15:59:08,747 : NetworkPlan [INFO] : Asserting Input Projections Match
2015-05-14 15:59:08,751 : NetworkPlan [INFO] : Aligning Network Nodes With Input Metrics
2015-05-14 15:59:25,884 : NetworkPlan [INFO] : Computing Pairwise Distances
2015-05-14 15:59:25,884 : NetworkPlan [INFO] : Using haversine Distance
2015-05-14 15:59:35,243 : NetworkPlan [INFO] : Directing Network Away From Roots
2015-05-14 15:59:36,022 : NetworkPlan [INFO] : Directing SUBGRAPH 1 / 6
2015-05-14 15:59:36,075 : NetworkPlan [INFO] : DONE!
2015-05-14 15:59:36,076 : NetworkPlan [INFO] : Directing SUBGRAPH 2 / 6
2015-05-14 15:59:36,109 : NetworkPlan [INFO] : DONE!
2015-05-14 15:59:36,109 : NetworkPlan [INFO] : Directing SUBGRAPH 3 / 6
2015-05-14 15:59:36,132 : NetworkPlan [INFO] : DONE!
2015-05-14 15:59:36,132 : NetworkPlan [INFO] : Directing SUBGRAPH 4 / 6
2015-05-14 15:59:36,170 : NetworkPlan [INFO] : DONE!
2015-05-14 15:59:36,171 : NetworkPlan [INFO] : Directing SUBGRAPH 5 / 6
2015-05-14 15:59:36,225 : NetworkPlan [INFO] : DONE!
2015-05-14 15:59:36,226 : NetworkPlan [INFO] : Directing SUBGRAPH 6 / 6
2015-05-14 15:59:36,239 : NetworkPlan [INFO] : DONE!
2015-05-14 15:59:36,834 : Sequencer   [INFO] : Converting The Network to a HashMap (Warning: this is time consuming for large Networks)
Traceback (most recent call last):
  File "/home/mr/modelrunner/scripts/mvmax_sequencer.py", line 22, in <module>
    results = model.sequence()
...
  File "/home/mr/miniconda/envs/sequencer/lib/python2.7/site-packages/scipy/sparse/base.py", line 793, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
MemoryError

**Comment by chrisnatali** [comment]
This is an issue with Sequencer.  Moved here: https://github.com/SEL-Columbia/Sequencer/issues/41
